# -*- coding: utf-8 -*-
require "#{File.dirname(__FILE__)}/_defines.rb"
require "#{File.dirname(__FILE__)}/_os.rb"
require "#{File.dirname(__FILE__)}/_bot.rb"
require "#{File.dirname(__FILE__)}/_util.rb"

require 'rake'



###################################
#
# BUILD_PROTOCOL
#
###################################
desc "build protocol"
task :build_protocol do |t, args|
  input_dir = "#{ROOT_DIR}/protocol"
  output_dir = "#{UNITY_PRJ_DIR}/Assets/AutoGenerated"

  ## START
  sh "flatc --csharp -o #{output_dir} #{Dir.glob("#{input_dir}/*.fbs").join(' ')}"
  ## END
end
